---
title: "Plate Reader"

---

Install the library
```{r}
#install.packages("readxl")
#install.packages("dyplyr")
library(readxl)
library(dplyr)
library(plyr) 

```

Read the data - You may add "numeric" to col_types - depends how temp you have
```{r}
data <- read_excel("DaneDlaPaniMadzi.xlsx", col_types = c("text", "text", "numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
names(data) <- gsub(" ", "_", names(data))
data
```
We dont need the first row - delete
```{r}
data <- data[-1,]
#cols = c( 3, 4, 5,6,7,8,9,10) 
#data[,cols] = apply(data[,cols], 2, function(x) as.numeric(as.character(x)))
data
```

```{r}
#data_s <- filter(data, grepl("S", Layout))
#data_b <-filter(data, grepl("B", Layout))

data_diff <-  data %>%
  group_by(grp = (row_number() - 1) %/% 2) %>%
  summarise_all(funs(ifelse(is.numeric(.), first(.) - last(.), first(.)))) %>%
  ungroup() %>%
  select(-grp)

data_diff
```

```{r}
data_diff <- select(data_diff, - Well_positions)
data_stat <- data_diff %>% 
            group_by(Layout) %>%
            summarise_each(funs(mean(.), sd(.))) %>%
            ungroup()
data_stat
```
Take only mean data and calculate QY
```{r}
data_mean <- data_stat %>% select(Layout, ends_with("_mean"))


data_mean <- data_mean %>% 
  group_by(Layout) %>% 
  mutate(Q18=FL_18_mean/.$FL_18_mean[.$Layout == "ST1_1"]*.$Abs_18_mean[.$Layout == "ST1_1"]/Abs_18_mean,
         Q25=FL_25_mean/.$FL_25_mean[.$Layout == "ST1_1"]*.$Abs_25_mean[.$Layout == "ST1_1"]/Abs_25_mean,
         Q37=FL_37_mean/.$FL_37_mean[.$Layout == "ST1_1"]*.$Abs_37_mean[.$Layout == "ST1_1"]/Abs_37_mean,
         Q42=FL_42_mean/.$FL_42_mean[.$Layout == "ST1_1"]*.$Abs_42_mean[.$Layout == "ST1_1"]/Abs_42_mean
         )

#DELETE CONTROL 
#data_mean <- data_mean[-6,]

#select only Q
data_Q <- data_mean %>% select(Layout, starts_with("Q"))
data_Q
```



Multiply values by constants 
```{r}
c <- (1.3325^2)/(1.4385^2)

t18 <- 0.0002*(2649.0219*18.5^(-1.5448))^0.6019
t25 <- 0.0002*(2649.0219*25.2^-1.5448)^0.6019
t37 <- 0.0002*(2649.0219*37.4^-1.5448)^0.6019
t42 <-  0.0002*(2649.0219*42.5^-1.5448)^0.6019

t18
t25
t37
t42

#calculate viscosity
data_Q2 <- data_Q %>% 
  group_by(Layout) %>% 
  mutate(vis18=((Q18*c*t18)/0.0002)^(1/0.6019),
         vis25=((Q25*c*t25)/0.0002)^(1/0.6019),
         vis37=((Q37*c*t37)/0.0002)^(1/0.6019),
         vis42=((Q42*c*t42)/0.0002)^(1/0.6019)
         ) %>% ungroup()
data_Q2
```

final data
```{r}
vis <- data_Q2 %>% select(Layout, starts_with("vis")) %>% ungroup()

vis_gat <- final %>% gather(temp, val, -one_of("Layout"))
```

Error propagation 
```{r}

error <- join(data_stat, data_Q2) 

error_calc <- error %>% 
  group_by(Layout) %>% 
  mutate(e18=((sqrt((FL_18_sd/FL_18_mean)^2+(FL_18_sd[.$Layout == "ST1_1"]/FL_18_mean[.$Layout == "ST1_1"])^2+(Abs_18_sd/Abs_18_mean)^2+(Abs_18_sd[.$Layout == "ST1_1"]/Abs_18_mean[.$Layout == "ST1_1"])^2)))*vis18,
         e25=((sqrt((FL_25_sd/FL_25_mean)^2+(FL_25_sd[.$Layout == "ST1_1"]/FL_25_mean[.$Layout == "ST1_1"])^2+(Abs_25_sd/Abs_25_mean)^2+(Abs_25_sd[.$Layout == "ST1_1"]/Abs_25_mean[.$Layout == "ST1_1"])^2)))*vis25,
         e37=((sqrt((FL_37_sd/FL_37_mean)^2+(FL_37_sd[.$Layout == "ST1_1"]/FL_37_mean[.$Layout == "ST1_1"])^2+(Abs_37_sd/Abs_37_mean)^2+(Abs_37_sd[.$Layout == "ST1_1"]/Abs_37_mean[.$Layout == "ST1_1"])^2)))*vis37,
         e42=((sqrt((FL_42_sd/FL_42_mean)^2+(FL_42_sd[.$Layout == "ST1_1"]/FL_42_mean[.$Layout == "ST1_1"])^2+(Abs_42_sd/Abs_42_mean)^2+(Abs_42_sd[.$Layout == "ST1_1"]/Abs_42_mean[.$Layout == "ST1_1"])^2)))*vis42
         )

errors<- error_calc %>% select(Layout, starts_with("e")) %>% ungroup()
errors

#*abs((1.3325^2)/(1.4385^2))*abs(Q18)
```
https://gist.github.com/kdauria/524eade46135f6348140 - function to add correlation factor
https://stackoverflow.com/questions/7549694/adding-regression-line-equation-and-r2-on-graph
```{r}
stat_smooth_func <- function(mapping = NULL, data = NULL,
                        geom = "smooth", position = "identity",
                        ...,
                        method = "auto",
                        formula = y ~ x,
                        se = TRUE,
                        n = 80,
                        span = 0.75,
                        fullrange = FALSE,
                        level = 0.95,
                        method.args = list(),
                        na.rm = FALSE,
                        show.legend = NA,
                        inherit.aes = TRUE,
                        xpos = NULL,
                        ypos = NULL) {
  layer(
    data = data,
    mapping = mapping,
    stat = StatSmoothFunc,
    geom = geom,
    position = position,
    show.legend = show.legend,
    inherit.aes = inherit.aes,
    params = list(
      method = method,
      formula = formula,
      se = se,
      n = n,
      fullrange = fullrange,
      level = level,
      na.rm = na.rm,
      method.args = method.args,
      span = span,
      xpos = xpos,
      ypos = ypos,
      ...
    )
  )
}


StatSmoothFunc <- ggproto("StatSmooth", Stat,
                      
                      setup_params = function(data, params) {
                        # Figure out what type of smoothing to do: loess for small datasets,
                        # gam with a cubic regression basis for large data
                        # This is based on the size of the _largest_ group.
                        if (identical(params$method, "auto")) {
                          max_group <- max(table(data$group))
                          
                          if (max_group < 1000) {
                            params$method <- "loess"
                          } else {
                            params$method <- "gam"
                            params$formula <- y ~ s(x, bs = "cs")
                          }
                        }
                        if (identical(params$method, "gam")) {
                          params$method <- mgcv::gam
                        }
                        
                        params
                      },
                      
                      compute_group = function(data, scales, method = "auto", formula = y~x,
                                               se = TRUE, n = 80, span = 0.75, fullrange = FALSE,
                                               xseq = NULL, level = 0.95, method.args = list(),
                                               na.rm = FALSE, xpos=NULL, ypos=NULL) {
                        if (length(unique(data$x)) < 2) {
                          # Not enough data to perform fit
                          return(data.frame())
                        }
                        
                        if (is.null(data$weight)) data$weight <- 1
                        
                        if (is.null(xseq)) {
                          if (is.integer(data$x)) {
                            if (fullrange) {
                              xseq <- scales$x$dimension()
                            } else {
                              xseq <- sort(unique(data$x))
                            }
                          } else {
                            if (fullrange) {
                              range <- scales$x$dimension()
                            } else {
                              range <- range(data$x, na.rm = TRUE)
                            }
                            xseq <- seq(range[1], range[2], length.out = n)
                          }
                        }
                        # Special case span because it's the most commonly used model argument
                        if (identical(method, "loess")) {
                          method.args$span <- span
                        }
                        
                        if (is.character(method)) method <- match.fun(method)
                        
                        base.args <- list(quote(formula), data = quote(data), weights = quote(weight))
                        model <- do.call(method, c(base.args, method.args))
                        
                        m = model
                        eq <- substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2, 
                                         list(a = format(coef(m)[1], digits = 3), 
                                              b = format(coef(m)[2], digits = 3), 
                                              r2 = format(summary(m)$r.squared, digits = 3)))
                        func_string = as.character(as.expression(eq))
                        
                        if(is.null(xpos)) xpos = min(data$x)*0.9
                        if(is.null(ypos)) ypos = max(data$y)*0.9
                        data.frame(x=xpos, y=ypos, label=func_string)
                        
                      },
                      
                      required_aes = c("x", "y")
)

```



PLOT the data
```{r}
final <- join(vis, errors)
#delete last column - ST1_1
final <- final %>% filter(!(Layout == "ST1_1"))
final_gat <- final %>%
  gather(key, value, -Layout) %>%
  extract(key, c("question", "temp"), "^([a-z]+)([0-9]+).*") %>%
  spread(question, value) 


#final_gat$temp <- as.numeric(final_gat$temp)

ggplot(final_gat, aes(x = as.numeric(temp), y = vis, group = Layout, col = Layout)) + 
   geom_errorbar(aes(ymin =vis - e, ymax = vis +e), width=.1)+
   scale_y_log10() +
  geom_point(position=pd, size=3, shape=21, fill="white") + 
   stat_smooth(method=lm, se = FALSE, linetype = "dashed", size = 0.2) +
  stat_smooth_func(geom="text",method="lm",hjust=0,parse=TRUE)+
  #geom_point(aes(col = Layout)) +
  theme_bw()
```

```{r}

final_gat_K <- final_gat %>% mutate(K = (1000/as.numeric(temp)+272.15))

ggplot(final_gat_K, aes(x = K, y = vis, group = Layout, col = Layout)) + 
   geom_errorbar(aes(ymin =vis - e, ymax = vis +e), width=.1)+
   geom_line()+ 
   scale_y_log10() +
  #geom_point(position=pd, size=3, shape=21, fill="white") + 
  #geom_point(aes(col = Layout)) +
  theme_bw()
```


